# ---------------------     Core
quarkus.application.name=pcb
quarkus.banner.enabled=false
quarkus.http.port=8080
%dev.quarkus.http.port=8090
# ---------------------     Docker
quarkus.container-image.build=false
quarkus.container-image.group=otomotive
quarkus.container-image.name=pcb
quarkus.container-image.tag=latest
# ---------------------     Swagger UI
# https://quarkus.io/guides/openapi-swaggerui
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.filter=true
quarkus.swagger-ui.theme=original
quarkus.swagger-ui.title=API PCB
quarkus.swagger-ui.footer=&#169; 2026 Otomotive
quarkus.smallrye-openapi.security-scheme-name=TBT
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.api-key-parameter-in=header
quarkus.smallrye-openapi.api-key-parameter-name=Authorization
